name: Update Latest

on:
  workflow_dispatch:
  push:


jobs:
  UpdateToLatest:
    name: Update to Latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: getRelease
        name: Fetch latest release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: photoprism/photoprism
      - name: Update Makefile
        run: |
          export VERSION=`echo "${{ steps.getRelease.outputs.release }}"|cut -d "-" -f 1`
          sed -i "s/DISTVERSION=.*/DISTVERSION=	g${VERSION}/g" Makefile
          sed -i "s/GH_TAGNAME=.*/GH_TAGNAME=	${{ steps.getRelease.outputs.release }}/g" Makefile
      - name: Build The Latest
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y gmake npm wget pkgconf git go121 portsnap ffmpeg p5-Image-ExifTool libheif vips bsddialog portconfig
            mkdir -p /var/db/portsnap && portsnap --interactive auto > dev/null
            fetch https://github.com/psa/libtensorflow1-freebsd-port/releases/download/1.15.5-pre-release-0/libtensorflow1-1.15.5-FreeBSD-13.0-AVX.pkg -o /tmp/libtf.pkg
            pkg add /tmp/libtf.pkg
          run: |
            git config --global --add safe.directory /home/runner/work/photoprism-freebsd-port/photoprism-freebsd-port
            make makesum
            make -j $(nproc)
            make makeplist >pkg-plist
            tail -n +2 pkg-plist >pkg-plist.tmp
            mv pkg-plist.tmp pkg-plist
            git status