name: Update Latest

on:
  workflow_dispatch:


jobs:
  UpdateToLatest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: getRelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: photoprism/photoprism
      - run: |
          VERSION=`echo "${{ steps.getRelease.outputs.release }}"|cut -d "-" -f 1``
          sed -i "s/DISTVERSION=.*/DISTVERSION=g${VERSION}/g" Makefile
          sed -i "s/GH_TAGNAME=.*/GH_TAGNAME=${{ steps.getRelease.outputs.release }}/g" Makefile
          cat Makefile
